### ISSUE TITLE
CAN Socket support?

### ISSUE THREAD

**Issue by vibnwis** [mjbots/fdcanusb#2]
Does it support CAN Socket?

**Comment by jpieper** [comment]
The daemon found here https://github.com/mjbots/fdcanusb/blob/master/sw/fdcanusb_daemon.cc can be used to provide a socketcan interface from the fdcanusb.

**Comment by vibnwis** [comment]
Many thanks for the response. However, having searched high and low, yet not seeing the hardware for your code.  What or where is the hardware?

**Comment by jpieper** [comment]
https://github.com/mjbots/fdcanusb/tree/master/hw

**Comment by jpieper** [comment]
When they are in stock, you can also buy them at https://mjbots.com/products/fdcanusb

**Comment by vibnwis** [comment]
The description of "serial-like" is confusing, despite me a embedded
engineer and familiar with CAN-bus not so sure it is a CAN-bus device or
Serial-like CAN-bus, please elaborate?

**Comment by jpieper** [comment]
When inserted into a USB port, it implements the USB CDC interface.  That means it looks like a virtual COM port to Windows or Linux.

When you use a terminal emulator like hyperterminal or minicom, it allows you to send commands which cause CAN-FD frames to be emitted out the other side.  CAN-FD frames that are successfully received, are reported as responses on that same USB CDC interface.

**Comment by vibnwis** [comment]
Thank you for the explanation. I need a USB-FDCAN adapter. Your product
does not suit my needs. Thank you

**Comment by jpieper** [comment]
No worries.  Although, a USB CAN-FD adapter is exactly what this is.  I'm not sure what else you would expect from such an adapter.

**Comment by vibnwis** [comment]
Simply, USB<->CANFD, so that I can have an FDCAN device on my PC through
USB.

**Comment by jpieper** [comment]
That is exactly what this device lets you do.

Every USB to CAN-FD adapter has a unique protocol on the PC side.  The fdcanusb's is documented in the README, and additionally there is the daemon linked above that lets it present as a linux socketcan device.

**Comment by vibnwis** [comment]
I re-visited your explanation, and realize that the serial-like is an emulation. Without emulation, it is a USB-FDCAN device. I need a device for my research studies. Hence, do not have much time for trouble-shooting. Is the product as CAN Socket promising or working. I can compile the Linux driver, but just wanting to know it is not stable, not a beta release, is it?

**Comment by jpieper** [comment]
It is plenty stable for mjbots' needs.  However, you may decide you'd rather get something like the PEAK USB CAN-FD adapter, which while significantly more expensive, is provided by a company with a longer history.

https://www.peak-system.com/PCAN-USB-FD.365.0.html?&L=1

**Comment by vibnwis** [comment]
However, the website says it is out of stock and sold out?

**Comment by jpieper** [comment]
Yes, as the website says, the ETA of new stock is approximately 1 week.

**Comment by vibnwis** [comment]
How does it take an order?

**Comment by jpieper** [comment]
If you are asking how to place an order at mjbots.com, you can wait until it is in stock, then pay with a credit card or google pay using the automated online checkout.

**Comment by vibnwis** [comment]
Got it! I was thinking if I can place an order now, and pay when it is in
stock. All good. Thanks

**Comment by jpieper** [comment]
Great!  I'll close this issue out for now then.  If you have more questions, don't hesitate to mail info@mjbots.com or joint the mjbots discord: https://discord.gg/W4hUpBb

**Comment by vibnwis** [comment]
Hi there,
The FDCAN USB adapter is available now. However, it does not ship to New Zealand. Can you help, please?

**Comment by jpieper** [comment]
Shipping to New Zealand should work.  Can you mail info@mjbots.com with a screenshot of any errors you are seeing?

**Comment by vibnwis** [comment]
Sent
