### ISSUE TITLE
Please, check if everything needed for flash is not ignored in .git

### ISSUE THREAD

**Issue by remixoff** [mjbots/fdcanusb#3]
`$ ./flash.sh 

Open On-Chip Debugger 0.10.0

Licensed under GNU GPL v2

For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html

embedded:startup.tcl:60: Error: Can't find interface/stlink.cfg
in procedure 'script' 

at file "embedded:startup.tcl", line 60
`

**after download the stlink.cfg:**

`$ ./flash.sh 

Open On-Chip Debugger 0.10.0

Licensed under GNU GPL v2

For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html

interface/stlink.cfg:8: Error: invalid command name "adapter"

in procedure 'script' 

at file "embedded:startup.tcl", line 60

at file "interface/stlink.cfg", line 8`

**after download proper stlink-v2.cfg:**

`$ ./flash.sh 

Open On-Chip Debugger 0.10.0

Licensed under GNU GPL v2

For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html

embedded:startup.tcl:60: Error: Can't find target/stm32g4x.cfg

in procedure 'script' 

at file "embedded:startup.tcl", line 60
`

**after download stm32g4x.cfg**

`$ ./flash.sh 

Open On-Chip Debugger 0.10.0

Licensed under GNU GPL v2

For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html

Info : auto-selecting first available session transport "hla_swd". To override use 'transport select <transport>'.

target/stm32g4x.cfg:33: Error: invalid command name "dap"

in procedure 'script' 

at file "embedded:startup.tcl", line 60

at file "target/stm32g4x.cfg", line 33
`

too much. Decided to flash via st-flash, but now figuring out if I should start flash from start of the memory, or need some alignments. 

PS: before that whole build was almost smoothly. Unmet dependencies are: `sudo apt install curl openocd` 
PPS: I was also surprised by not existing curl in Ubuntu 20

**Comment by jpieper** [comment]
The README had mentioned that some openocd's did not support the processor in the fdcanusb.  Since then, upstream 0.11.0 was released, which does have support.  It is included in Ubuntu 22.04, so I've just upped the minimum build requirement to that:

https://github.com/mjbots/fdcanusb/commit/8498001669f3600ab38d9354f805d563d8887492
https://github.com/mjbots/fdcanusb/commit/36789b84dd5530a48e8da899750c39ef3ef6b77b
