### ISSUE TITLE
Configuration is not saved well

### ISSUE THREAD

**Issue by remixoff** [mjbots/fdcanusb#4]
``` 
conf set can.restricted_mode  0
OK
conf write
OK
conf get can.restricted_mode 
ERR error reading
```

**Comment by jpieper** [comment]
Likely you used backspace or other non-printable characters.  While human readable, the protocol isn't necessarily human friendly.

```
conf enumerate
```

Will also display all configuration.  Can you try again, perhaps pasting to avoid having to backspace?

**Comment by jpieper** [comment]
Closing this as there as been no response.
