### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by AoyunTech** [mjbots/fdcanusb#5]
Hi Josh,
 Would you know how to fix this build errs?

Thanks

~/github/mjbots/fdcanusb$ ./tools/bazel build //fw:fdcanusb.bin
Downloading bazel 5.4.1 from https://github.com/bazelbuild/bazel/releases/download/5.4.1/bazel-5.4.1-linux-x86_64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:32 --:--:--     0
100 49.4M  100 49.4M    0     0  45333      0  0:19:03  0:19:03 --:--:-- 1738k
Traceback (most recent call last):
  File "./tools/bazel", line 108, in <module>
    main()
  File "./tools/bazel", line 101, in main
    download_bazel(bazel_bin_loc)
  File "./tools/bazel", line 88, in download_bazel
    raise RuntimeError(
RuntimeError: bazel sha256 does not match, expected e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 got 5d90515f84b5ee1fd6ec22ee9e83103e77ed1a907ee5eec198fef3a5b45abf13

**Comment by jpieper** [comment]
You likely have a proxy or something that is modifying the contents of the file that it is downloading: https://github.com/bazelbuild/bazel/releases/download/5.4.1/bazel-5.4.1-linux-x86_64  

I just downloaded it here again and got the expected hash of 5d90515f84b5ee1fd6ec22ee9e83103e77ed1a907ee5eec198fef3a5b45abf13 which is what is present in https://github.com/mjbots/fdcanusb/blob/7b0a188b39cb8ea94958e9601762a55b619bf2a0/WORKSPACE#L20

**Comment by AoyunTech** [comment]
> You likely have a proxy or something that is modifying the contents of the file that it is downloading: https://github.com/bazelbuild/bazel/releases/download/5.4.1/bazel-5.4.1-linux-x86_64
> 
> I just downloaded it here again and got the expected hash of 5d90515f84b5ee1fd6ec22ee9e83103e77ed1a907ee5eec198fef3a5b45abf13 which is what is present in
> 
> https://github.com/mjbots/fdcanusb/blob/7b0a188b39cb8ea94958e9601762a55b619bf2a0/WORKSPACE#L20

Hi Josh,
It's my mistakes.

Thanks for your reply!
Thanks

But i missed another issue when retry building again.
LOG as
1:~/github/mjbots/fdcanusb$ ./tools/bazel build //fw:fdcanusb.bin
Traceback (most recent call last):
  File "./tools/bazel", line 107, in <module>
    main()
  File "./tools/bazel", line 102, in main
    os.execv(bazel_bin_loc, ['bazel', ] + sys.argv[1:])
OSError: [Errno 8] Exec format error
 
Hope your suggestions please.

**Comment by jpieper** [comment]
The build process is only supported on a x64 Linux system.  I'm guessing you have a different architecture or OS.
