### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by bybayin** [mjbots/fdcanusb#6]
![微信截图_20241016075641](https://github.com/user-attachments/assets/64201faa-a11c-4067-8d7b-1b32043121e1)
Hello, may I ask how to solve this error when I build the code? Thank you very much for your help

**Comment by jpieper** [comment]
What operating system are you using?  How did you clone the repository?  It looks like the `tools/bazel` file has possibly become corrupted.

**Comment by bybayin** [comment]
> What operating system are you using? How did you clone the repository? It looks like the `tools/bazel` file has possibly become corrupted.

Good evening, Mr. Jpieper. I just recloned the code and recompiled it, and it passed. It seems that it was not a wise choice to directly copy and clone the code library from the Windows system. Thank you for your explanation. Thank you.

**Comment by jpieper** [comment]
Great, I'm glad you got it working!
