### ISSUE TITLE
Could not detect fdcanusb

### ISSUE THREAD

**Issue by bybayin** [mjbots/fdcanusb#7]
Hello, I have a problem and I was wondering if you could help me. When I was trying to connect to the FDCANUSB, I got an unexpected message in the console that says "Could not detect FDCANUSB." How can I resolve this issue?
![cmd](https://github.com/user-attachments/assets/da033f86-500c-4c9a-bbcb-f3b0ea00a858)
![usb](https://github.com/user-attachments/assets/e222a9db-89cf-45e9-9c70-838651cdeb1f)

**Comment by jpieper** [comment]
Do you have a fdcanusb connected to your computer?  

Is the red PWR light illuminated on the fdcanusb?

Is this a fdcanusb you purchased from mjbots.com?

**Comment by bybayin** [comment]
> 您的计算机是否连接了 fdcanusb？
> 
> fdcanusb 上的红色 PWR 灯是否亮起？
> 
> 这是您从 mjbots.com 购买的 fdcanusb 吗？

This is the source code I compiled for fdcanUSB and burned it onto my custom PCB board. The burning program was successful, but the PWR light did not turn on after powering on. The computer USB recognized this device as DFU in FS Mode

**Comment by jpieper** [comment]
mjbots does not provide support for custom built boards.  If you have further issues, you should ask in the mjbots Discord in the #ibuiltit channel: https://discord.gg/W4hUpBb

That said, it sounds like you have not set the option bytes.  There is a script in the moteus repo: https://github.com/mjbots/moteus/blob/main/fw/program_option_bytes.sh
